### ISSUE TITLE
SoyToPySrcCompiler: java.lang.ClassCastException

### ISSUE THREAD

**Issue by mapx** [google/closure-templates#100]
Failed to compile soy files into python templates with `soy-2016-01-12-SoyToPySrcCompiler.jar`:
```
java.lang.ClassCastException: com.google.template.soy.soytree.RawTextNode cannot be cast to com.google.template.soy.soytree.SoyNode$MsgPlaceholderInitialNode
        at com.google.template.soy.pysrc.internal.MsgFuncGenerator.collectVarNameListAndToPyExprMap(MsgFuncGenerator.java:213)
        at com.google.template.soy.pysrc.internal.MsgFuncGenerator.pyFuncForGeneralMsg(MsgFuncGenerator.java:145)
        at com.google.template.soy.pysrc.internal.MsgFuncGenerator.getPyExpr(MsgFuncGenerator.java:130)
        at com.google.template.soy.pysrc.internal.GenPyExprsVisitor.visitMsgFallbackGroupNode(GenPyExprsVisitor.java:216)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:71)
        at com.google.template.soy.pysrc.internal.GenPyExprsVisitor.exec(GenPyExprsVisitor.java:113)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitChildren(GenPyCodeVisitor.java:169)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitIfNode(GenPyCodeVisitor.java:370)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:91)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitChildren(GenPyCodeVisitor.java:179)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.generateFunctionBody(GenPyCodeVisitor.java:891)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitTemplateNode(GenPyCodeVisitor.java:288)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:155)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:63)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitSoyFileNode(GenPyCodeVisitor.java:255)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:61)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.visitSoyFileSetNode(GenPyCodeVisitor.java:197)
        at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:60)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor$Impl.exec(GenPyCodeVisitor.java:150)
        at com.google.template.soy.pysrc.internal.GenPyCodeVisitor.gen(GenPyCodeVisitor.java:128)
        at com.google.template.soy.pysrc.internal.PySrcMain.genPySrc(PySrcMain.java:117)
        at com.google.template.soy.pysrc.internal.PySrcMain.genPyFiles(PySrcMain.java:155)
        at com.google.template.soy.SoyFileSet.compileToPySrcFiles(SoyFileSet.java:1137)
        at com.google.template.soy.SoyToPySrcCompiler.execMain(SoyToPySrcCompiler.java:229)
        at com.google.template.soy.SoyToPySrcCompiler.access$100(SoyToPySrcCompiler.java:49)
        at com.google.template.soy.SoyToPySrcCompiler$1.main(SoyToPySrcCompiler.java:168)
        at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:195)
        at com.google.template.soy.MainClassUtils.run(MainClassUtils.java:188)
        at com.google.template.soy.SoyToPySrcCompiler.main(SoyToPySrcCompiler.java:164)
```

**Comment by lukesandberg** [comment]
This bug was fixed internally but the fix hasn't been sync'd out yet...  i believe @mikesamuel  is working on a release

**Comment by mapx** [comment]
Bravo! Fixed!
Thanks!
