### ISSUE TITLE
SoyAutoescapeException: Error while re-contextualizing template

### ISSUE THREAD

**Issue by nicks** [google/closure-templates#11]
This template blows up the compiler

```
{namespace views.postHtml autoescape="contextual"}

/**
 * @param baseUrl
 * @param path
 */
{template .x}
  <a href='{call .url data="all" /}'>
{/template}

/**
 * @param baseUrl
 * @param path
 */
{template .url}
  {if $baseUrl}{$baseUrl}{/if}/
  {$path}
{/template}
```

Here's the stack trace:

```
com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException: In file postHtml.soy:8, template views.postHtml.x: Error while re-contextualizing template views.postHtml.url in context (Context URI NORMAL URI SINGLE_QUOTE START):
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException.createCausedWithoutMetaInfo(SoyAutoescapeException.java:58)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException.createCausedWithNode(SoyAutoescapeException.java:93)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.contextualizeCallee(InferenceEngine.java:633)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.inferCallSite(InferenceEngine.java:601)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitCallNode(InferenceEngine.java:245)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitCallBasicNode(AbstractSoyNodeVisitor.java:304)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:110)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:56)
[template-compiler]     at com.google.template.soy.basetree.AbstractNodeVisitor.visitChildren(AbstractNodeVisitor.java:59)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitChildren(AbstractSoyNodeVisitor.java:129)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitTemplateNode(InferenceEngine.java:201)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:160)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:66)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.exec(InferenceEngine.java:174)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.infer(InferenceEngine.java:149)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.inferTemplateEndContext(InferenceEngine.java:106)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.ContextualAutoescaper.rewrite(ContextualAutoescaper.java:163)
[template-compiler]     at com.google.template.soy.SoyFileSet.doContextualEscaping(SoyFileSet.java:1008)
[template-compiler]     at com.google.template.soy.SoyFileSet.runMiddleendPasses(SoyFileSet.java:990)
[template-compiler]     at com.google.template.soy.SoyFileSet.compileToJsSrcFiles(SoyFileSet.java:924)
[template-compiler]     at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:303)
[template-compiler]     at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
[template-compiler] Caused by: com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException: In file postHtml.soy:17, template views.postHtml.url__C33f6: Cannot determine which part of the URL {$path} is in.
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException.createWithoutMetaInfo(SoyAutoescapeException.java:42)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.SoyAutoescapeException.createWithNode(SoyAutoescapeException.java:76)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.getContextAfterEscaping(InferenceEngine.java:862)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.access$700(InferenceEngine.java:79)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitPrintNode(InferenceEngine.java:480)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:87)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:56)
[template-compiler]     at com.google.template.soy.basetree.AbstractNodeVisitor.visitChildren(AbstractNodeVisitor.java:59)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitChildren(AbstractSoyNodeVisitor.java:129)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitTemplateNode(InferenceEngine.java:201)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:160)
[template-compiler]     at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:66)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.exec(InferenceEngine.java:174)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.infer(InferenceEngine.java:149)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.inferTemplateEndContext(InferenceEngine.java:106)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.hypothesizeContextualization(InferenceEngine.java:712)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.determineContextualization(InferenceEngine.java:662)
[template-compiler]     at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.contextualizeCallee(InferenceEngine.java:630)
[template-compiler]     ... 19 more
```

This is using Closure templates release 2014-04-22.

**Comment by jwheeler31** [comment]
I didn't have this exact same problem, but a similar one was due to missing a closing double quote on an html attribute.
