### ISSUE TITLE
StackOverflowError during template compilation

### ISSUE THREAD

**Issue by SerCeMan** [google/closure-templates#118]
Hello!

First of all, thank you for the great template library! 

We have a decent amount templates and recently we started getting SOE during initial soy templates compilation:
```java
SoyFileSet.Builder soyFileSetBuilder = SoyFileSet.builder();
// ...
return soyFileSetBuilder.build().compileToTofu();
``` 
Error:
```
       ...
       ...
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4801)
	at java.util.regex.Pattern$Prolog.match(Pattern.java:4741)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:637)
	at com.google.template.soy.parsepasses.contextautoesc.RawTextContextUpdater.processNextToken(RawTextContextUpdater.java:219)
	at com.google.template.soy.parsepasses.contextautoesc.RawTextContextUpdater.processRawText(RawTextContextUpdater.java:83)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitRawTextNode(InferenceEngine.java:266)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:66)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:54)
	at com.google.template.soy.basetree.AbstractNodeVisitor.visitAll(AbstractNodeVisitor.java:78)
	at com.google.template.soy.basetree.AbstractNodeVisitor.visitChildren(AbstractNodeVisitor.java:56)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitChildren(AbstractSoyNodeVisitor.java:124)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitSoyNode(InferenceEngine.java:590)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitIfCondNode(AbstractSoyNodeVisitor.java:255)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:92)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.exec(InferenceEngine.java:226)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.infer(InferenceEngine.java:201)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.access$900(InferenceEngine.java:80)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.propagateAcrossDisjunction(InferenceEngine.java:836)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitIfNode(InferenceEngine.java:409)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:91)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:54)
	at com.google.template.soy.basetree.AbstractNodeVisitor.visitAll(AbstractNodeVisitor.java:78)
	at com.google.template.soy.basetree.AbstractNodeVisitor.visitChildren(AbstractNodeVisitor.java:56)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitChildren(AbstractSoyNodeVisitor.java:124)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.visitTemplateNode(InferenceEngine.java:253)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:155)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:63)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine$ContextPropagatingVisitor.exec(InferenceEngine.java:226)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.infer(InferenceEngine.java:201)
	at com.google.template.soy.parsepasses.contextautoesc.InferenceEngine.inferTemplateEndContext(InferenceEngine.java:109)
	at com.google.template.soy.parsepasses.contextautoesc.ContextualAutoescaper.rewrite(ContextualAutoescaper.java:182)
	at com.google.template.soy.SoyFileSet.doContextualEscaping(SoyFileSet.java:1236)
	at com.google.template.soy.SoyFileSet.runMiddleendPasses(SoyFileSet.java:1207)
	at com.google.template.soy.SoyFileSet.compileForServerRendering(SoyFileSet.java:902)
	at com.google.template.soy.SoyFileSet.compileToTofu(SoyFileSet.java:814)
```

The easiest way to reproduce the problem is to decrease jvm stack size (-Xss).

**Comment by SerCeMan** [comment]
We are low on memory and can't increase the stack size. We also tried `SoyToJbcSrcCompiler`, but it doesn't work.

What do you think about using different regex library like [re2j](https://github.com/google/re2j)?

**Comment by lukesandberg** [comment]
I would guess that this is the regex causing trouble
https://github.com/google/closure-templates/blob/8c383d18fd8bfc3a4e68167ff96821011940638a/java/src/com/google/template/soy/parsepasses/contextautoesc/RawTextContextUpdater.java#L932


I fixed a bug with that particular regex in https://github.com/google/closure-templates/commit/e1a9d36a371c303b316ff3d9df22ec547b81c4ba

(the trick was to make one half of the alternation greedier)

I also modified the exception reporting in this situation so we could tell which regex failed, but it doesn't look like you are using that code.  Is this reproducible with closure templates built from head?

At the time i considered switching to re2j, but that would be a lot of work since a number of our regexes would have to be completely rewritten (re2j doesn't support negative lookahead iirc).  We are however pursuing an alternate plan to move more of our html validation into the soy parser and out of the autoescaper.  In the long run i expect a lot of these complex regexes to naturally disappear as part of that work.

**Comment by SerCeMan** [comment]
Yes, I just made a mistake and didn't update the app to a new version of soy properly. Thank you, latest version looks good. 

But do you have any plans for `SoyToJbcSrcCompiler`. Or it is more like experimental project?

**Comment by lukesandberg** [comment]
SoyToJbcSrcCompiler is no longer considered experimental.  we are running it in a number of large applications at google and have seen some positive results (faster rendering, better thread utilization).  The main thing is that we need to publish some examples.  

There is documentation of incompatibilities with Tofu here: https://github.com/google/closure-templates/tree/master/java/src/com/google/template/soy/jbcsrc#compatibility

in general jbcsrc is more compatible with jssrc.

**Comment by SerCeMan** [comment]
@lukesandberg,

We were getting these errors with jbcsrc:
```
Guice.createInjector(new PrecompiledSoyModule()).getInstance(Key.get(SoySauce.class, Precompiled.class))
```
->
```
Caused by: java.lang.IncompatibleClassChangeError: com.google.template.soy.jbcsrc.gen.i18n.scripts and com.google.template.soy.jbcsrc.gen.i18n.scripts$Factory disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at com.google.template.soy.jbcsrc.shared.CompiledTemplates$TemplateData.<init>(CompiledTemplates.java:223)
	at com.google.template.soy.jbcsrc.shared.CompiledTemplates.loadFactory(CompiledTemplates.java:180)
	at com.google.template.soy.jbcsrc.shared.CompiledTemplates.getTemplateData(CompiledTemplates.java:151)
	at com.google.template.soy.jbcsrc.shared.CompiledTemplates.getTemplateFactory(CompiledTemplates.java:102)
	at com.google.template.soy.jbcsrc.api.SoySauceImpl.renderTemplate(SoySauceImpl.java:131)
	at com.google.template.soy.jbcsrc.api.SoySauceImpl.renderTemplate(SoySauceImpl.java:59)
```

and

```
soyFileSetBuilder.build().compileTemplates();
```
->
```
Caused by: java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at com.google.template.soy.jbcsrc.SoyClassWriter.toClassData(SoyClassWriter.java:150)
	at com.google.template.soy.jbcsrc.TemplateCompiler.compile(TemplateCompiler.java:152)
	at com.google.template.soy.jbcsrc.CompilingClassLoader.getClassData(CompilingClassLoader.java:64)
	at com.google.template.soy.jbcsrc.AbstractMemoryClassLoader.findClass(AbstractMemoryClassLoader.java:88)
	at com.google.template.soy.jbcsrc.AbstractMemoryClassLoader.loadClass(AbstractMemoryClassLoader.java:74)
```

**Comment by lukesandberg** [comment]
could you open another issue and provide more information (how big is this template?)
