### ISSUE TITLE
SoyMsgExtractor crashes when given a plural

### ISSUE THREAD

**Issue by nicks** [google/closure-templates#123]
Repro steps:
1) Create a soy template with a plural
```
/**
 * Say hello to a list of people.
 * @param names List of names of the people to say hello to.
 */
{template .helloNames}
  {msg desc="names"}
    {plural length($names)}
      {case 0}Hello nobody!
      {case 1}Hello {$names[0]}
      {default}Hello sheeple
    {/plural}
  {/msg}
{/template}
```

2) `java -jar target/soy-2016-07-21-SoyMsgExtractor.jar --srcs example.soy --outputFile foo.xlf`

Expected result:
should output a valid xlf

Actual result:
```
java.lang.ClassCastException: com.google.template.soy.msgs.restricted.SoyMsgPluralPart cannot be cast to com.google.template.soy.msgs.restricted.SoyMsgPlaceholderPart
	at com.google.template.soy.xliffmsgplugin.XliffGenerator.generateXliff(XliffGenerator.java:114)
	at com.google.template.soy.xliffmsgplugin.XliffMsgPlugin.generateExtractedMsgsFile(XliffMsgPlugin.java:45)
	at com.google.template.soy.msgs.SoyMsgBundleHandler.writeToExtractedMsgsFile(SoyMsgBundleHandler.java:182)
```

**Comment by nicks** [comment]
i'm going to try implementing a version of this spec
http://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html
which provides some guidance of how plurals from other systems should interoperate with xliff, given that there's no official xliff/plurals standard.
