### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.google.template.soy.data.internalutils.NodeContentKinds

### ISSUE THREAD

**Issue by paladox** [google/closure-templates#130]
Hi, trying to update gerrit to this new version results in error java.lang.NoClassDefFoundError: Could not initialize class com.google.template.soy.data.internalutils.NodeContentKinds

See https://gerrit-review.googlesource.com/#/c/99739/ please.

**Comment by dpursehouse** [comment]
Full stack trace of the exception is:

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.template.soy.data.internalutils.NodeContentKinds
	at com.google.template.soy.soytree.CommandTagAttribute.valueAsContentKind(CommandTagAttribute.java:158)
	at com.google.template.soy.soytree.TemplateBasicNodeBuilder.setCommandValues(TemplateBasicNodeBuilder.java:100)
	at com.google.template.soy.soyparse.SoyFileParser.TemplateHelper(SoyFileParser.java:663)
	at com.google.template.soy.soyparse.SoyFileParser.Template(SoyFileParser.java:620)
	at com.google.template.soy.soyparse.SoyFileParser.SoyFile(SoyFileParser.java:514)
	at com.google.template.soy.soyparse.SoyFileParser.parseSoyFile(SoyFileParser.java:372)
	at com.google.template.soy.SoyFileSetParser.parseSoyFileHelper(SoyFileSetParser.java:176)
	at com.google.template.soy.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:127)
	at com.google.template.soy.SoyFileSetParser.parse(SoyFileSetParser.java:98)
	at com.google.template.soy.SoyFileSet.parse(SoyFileSet.java:1242)
	at com.google.template.soy.SoyFileSet.parse(SoyFileSet.java:1203)
	at com.google.template.soy.SoyFileSet.compileForServerRendering(SoyFileSet.java:926)
	at com.google.template.soy.SoyFileSet.compileToTofu(SoyFileSet.java:845)
	at com.google.gerrit.server.mail.send.MailSoyTofuProvider.get(MailSoyTofuProvider.java:89)
	at com.google.gerrit.server.mail.send.MailSoyTofuProvider.get(MailSoyTofuProvider.java:1)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
	at com.sun.proxy.$Proxy80.create(Unknown Source)
	at com.google.gerrit.server.change.PostReviewers.emailReviewers(PostReviewers.java:474)
	at com.google.gerrit.server.change.PostReviewers$Op.postUpdate(PostReviewers.java:426)
	at com.google.gerrit.server.update.ReviewDbBatchUpdate.executePostOps(ReviewDbBatchUpdate.java:901)
	at com.google.gerrit.server.update.ReviewDbBatchUpdate.execute(ReviewDbBatchUpdate.java:341)
	at com.google.gerrit.server.update.ReviewDbBatchUpdate.execute(ReviewDbBatchUpdate.java:421)
	at com.google.gerrit.server.update.ReviewDbBatchUpdate.execute(ReviewDbBatchUpdate.java:416)
	at com.google.gerrit.server.change.PostReviewers.apply(PostReviewers.java:164)
	at com.google.gerrit.server.api.changes.ChangeApiImpl.addReviewer(ChangeApiImpl.java:392)
	at com.google.gerrit.server.api.changes.ChangeApiImpl.addReviewer(ChangeApiImpl.java:386)
	at com.google.gerrit.acceptance.server.mail.MailMetadataIT.metadataOnNewChange(MailMetadataIT.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:259)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The class `com.google.template.soy.data.internalutils.NodeContentKinds` exists in the soy jar file that we have on the classpath.  I suspect the actual problem is that it can't find some other class or resource that it needs.

FWIW we don't get the same problem when upgrading from `2016-08-09` to `2016-08-25`.

It's not possible to bisect the open source version to figure out what caused it, because:

```
closure-templates $ git log --oneline --no-merges release-2016-08-25..release-2017-02-01
bd7fa7ad Release candidate 2017-02-01
7dae5a1a mondo-commit since MOE is refusing to migrate individual changes.
```

**Comment by davido** [comment]
I think that `com.google.common.html.types` is missing:

```
+maven_jar(
+    name = "html_types",
+    artifact = "com.google.common.html.types:types:1.0.4",
+    sha1 = "2adf4c8bfccc0ff7346f9186ac5aa57d829ad065",
 )
```

**Comment by dpursehouse** [comment]
Yep, that was the problem.  Thanks.

This issue can be closed, then.

**Comment by paladox** [comment]
Thanks.
