### ISSUE TITLE
java.io.FileNotFoundException grid.soy.js (No such file or directory)

### ISSUE THREAD

**Issue by fanqi** [google/closure-templates#134]
```
[08:58:22] Starting 'metal:render:soy'...

/usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/lib/handleError.js:13
                throw err;
                ^
Error: Compile error:
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.io.FileNotFoundException: /usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/temp/metal/temp/metal/pages/docs/patterns/grid.soy.js (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.google.common.io.Files.newWriter(Files.java:103)
        at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsFiles(IncrementalDomSrcMain.java:174)
        at com.google.template.soy.SoyFileSet.compileToIncrementalDomSrcFiles(SoyFileSet.java:1094)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.compile(SoyToIncrementalDomSrcCompiler.java:87)
        at com.google.template.soy.AbstractSoyCompiler.compile(AbstractSoyCompiler.java:227)
        at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:187)
        at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:49)
        at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:149)
        at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:255)
        at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:146)
        at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:138)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:64)


```

**Comment by fanqi** [comment]
i mkdir /usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/temp，it work successfully。

Are there any other way?

**Comment by mikesamuel** [comment]
What flags are you passing to the idom compiler?
