### ISSUE TITLE
NPE on Xliff URL locale when upgrading from soy 2017-02-01 to 2017-04-23

### ISSUE THREAD

**Issue by tntim96** [google/closure-templates#135]
The following code ran fine in soy `2017-02-01`, but fails after upgrading to `2017-04-13`:

```
            URL resourceUrl = getResourceUrl(resourceName);
            if (resourceUrl != null) {
                SoyMsgBundle msgBundle = new SoyMsgBundleHandler(new XliffMsgPlugin()).createFromResource(resourceUrl);
                renderer.setMsgBundle(msgBundle);
            }
```
The resource is a file that exists, `file:/home/..somepath..//translations/form_element_translation_fr.xlf`, and the stack-trace is as follows:

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.template.soy.msgs.restricted.SoyMsg$Builder.setLocaleString(SoyMsg.java:82)
	at com.google.template.soy.xliffmsgplugin.XliffParser$XliffSaxHandler.endElement(XliffParser.java:184)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at com.google.template.soy.xliffmsgplugin.XliffParser.parseXliffTargetMsgs(XliffParser.java:73)
	at com.google.template.soy.xliffmsgplugin.XliffMsgPlugin.parseTranslatedMsgsFile(XliffMsgPlugin.java:50)
	at com.google.template.soy.msgs.SoyMsgBundleHandler.createFromResource(SoyMsgBundleHandler.java:140)
```

The `localeString` is null, but it's not clear where this should be set and why it has changed.

**Comment by lukesandberg** [comment]
the parser looks for a 'target-language' attribute on the <file> element in
the xliff

We can potentially change the parser to allow for this attribute to not be
present (as it was before), but it will prevent soy from inferring the
correct language directionality.

would you be willing to share the xliff file? (feel free to redact the
message contents if they are sensitive)

**Comment by tntim96** [comment]
That's OK, we can add it in. I thought the target language might be inferred from the file name which ends in `fr`. It works OK after changing from:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="SoyMsgBundle" datatype="x-soy-msg-bundle" xml:space="preserve" source-language="en">
    <body>
      <trans-unit id="21641575311466062" datatype="html">
        <source>Hello</source>
        <target xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">Bonjour</target>
        <note priority="1" from="description">Hello</note>
      </trans-unit>
    </body>
  </file>
</xliff>
```
...to...
```XML
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="SoyMsgBundle" datatype="x-soy-msg-bundle" xml:space="preserve" source-language="en" target-language="fr">
    <body>
      <trans-unit id="21641575311466062" datatype="html">
        <source>Hello</source>
        <target xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">Bonjour</target>
        <note priority="1" from="description">Hello</note>
      </trans-unit>
    </body>
  </file>
</xliff>
```
...(i.e. adding in the `target-language="fr"`).
