### ISSUE TITLE
SoyProtoTypeProvider NPE

### ISSUE THREAD

**Issue by pcj** [google/closure-templates#148]
Stumbling towards using a `descriptor.proto` as a dependency for a proto that imports `google.protobuf.FileDescriptorSet`.  Anyhoo, appears that [SoyProtoTypeProvider.java#L157](https://github.com/google/closure-templates/blob/b3cb7780c8e5377c662cff758bc86ce9663c9c67/java/src/com/google/template/soy/types/proto/SoyProtoTypeProvider.java#L157) can return a null value.

```python
closure_js_proto_library(
    name = "workspace_closure",
    srcs = [
        "workspace.proto",
    ],
    deps = [
        "//proto/google/protobuf:descriptor_closure_js_proto",
    ],    
    visibility = ["//visibility:public"],
)
```

```
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.lang.NullPointerException
	at com.google.template.soy.types.proto.SoyProtoTypeProvider$Builder.buildDescriptor(SoyProtoTypeProvider.java:158)
	at com.google.template.soy.types.proto.SoyProtoTypeProvider$Builder.buildDescriptor(SoyProtoTypeProvider.java:160)
	at com.google.template.soy.types.proto.SoyProtoTypeProvider$Builder.walkAll(SoyProtoTypeProvider.java:143)
	at com.google.template.soy.types.proto.SoyProtoTypeProvider$Builder.build(SoyProtoTypeProvider.java:174)
	at com.google.template.soy.SoyFileSet$Builder.build(SoyFileSet.java:223)
	at com.google.template.soy.SoyToJsSrcCompiler.compile(SoyToJsSrcCompiler.java:214)
	at com.google.template.soy.AbstractSoyCompiler.compile(AbstractSoyCompiler.java:241)
	at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:200)
	at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:43)
	at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:168)
	at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:246)
	at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:164)
	at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:156)
	at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:192)
```

**Comment by pcj** [comment]
Here's what I think the problem was:

When compiling the `descriptor.proto`, the relative filepath that got compiled into the FileDescriptorSet (via `--descriptor_set_out`)  was `src/google/protobuf/descriptor.proto`.  During the SoyProtoTypeProvider builder phase, it was looking for `google/protobuf/descriptor.proto` and the key lookup failed, causing the null pointer exception.

By changing the protoc command to compile from inside `src/` rather than from the root of `google/protobuf`, the issue is resolved.

So, still a bug but has a "workaround" (i.e., using the protoc tool as intended).

**Comment by lukesandberg** [comment]
Thanks, there isn't much we can do about that from the soy side.  But i can provide a better error message :)
