### ISSUE TITLE
:private:apps:commerce:commerce-cart-taglib:transpileJS FAILED

### ISSUE THREAD

**Issue by wandjini** [google/closure-templates#153]
java.io.FileNotFoundException: /tmp/metal-tools-soy/add_to_cart/AddToCart.soy.js (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.google.common.io.Files.newWriter(Files.java:98)
        at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsFiles(IncrementalDomSrcMain.java:166)
        at com.google.template.soy.SoyFileSet.compileToIncrementalDomSrcFiles(SoyFileSet.java:1131)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.compile(SoyToIncrementalDomSrcCompiler.java:69)
        at com.google.template.soy.AbstractSoyCompiler.compile(AbstractSoyCompiler.java:227)
        at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:186)
        at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:43)
        at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:158)
        at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:246)
        at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:154)
        at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:146)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:61)

:private:apps:commerce:commerce-cart-taglib:transpileJS FAILED

**Comment by emspishak** [comment]
Hello, unfortunately I don't have enough details to understand your issue. Could you please post detailed reproduction steps so that I can reproduce your issue?
