### ISSUE TITLE
INTERNAL SOY ERROR deploying Emporio

### ISSUE THREAD

**Issue by klipin** [google/closure-templates#166]
Hi,
trying to deploy Liferay Commerce (Emporio) with command: 
D:\Program Files\lfry-ws\com-liferay-commerce-7.1.x>.\gradlew.bat deploy -Dbuild.profile=portal

in configuration:
* Lfry Workspace + 
* bundle 7.1 + 
* Emporio zip from 01.10.2018 +
* Windows 7

I get the the following error:

":apps:commerce:commerce-cart-taglib:transpileJS
Running 'build'...
Compiling soy
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.io.FileNotFoundException: \tmp\metal-tools-soy\add_to_cart\AddToCart.soy.js (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.common.io.Files.newWriter(Files.java:98)
        at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsFiles(IncrementalDomSrcMain.java:166)
        at com.google.template.soy.SoyFileSet.compileToIncrementalDomSrcFiles(SoyFileSet.java:1131)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.compile(SoyToIncrementalDomSrcCompiler.java:69)
        at com.google.template.soy.AbstractSoyCompiler.compile(AbstractSoyCompiler.java:227)
        at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:186)
        at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:43)
        at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:158)
        at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:246)
        at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:154)
        at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:146)
        at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:61)

:apps:commerce:commerce-cart-taglib:transpileJS FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:commerce:commerce-cart-taglib:transpileJS'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 36.717 secs
"

**Comment by iteriani** [comment]
We released a new Incremental DOM Src compiler, so this should be checked again if it works.
