### ISSUE TITLE
Found error where declared syntax version 2.0 is not satisfied

### ISSUE THREAD

**Issue by Vadorequest** [google/closure-templates#34]
I'm getting started following this tutorial: https://developers.google.com/closure/templates/docs/helloworld_js

But I cannot compile the `.soy` file using command line, I get this error:
```
java -jar SoyToJsSrcCompiler.jar --outputPathFormat cb.js --srcs cb.soy
Exception in thread "main" com.google.template.soy.base.SoySyntaxException: Found error where declared syntax version 2.0 is not satisfied: In file cb
.soy:2, template ns.templates.cb.cb: Tag {template .cb}: Template is missing SoyDoc.
        at com.google.template.soy.base.SoySyntaxException.createWithoutMetaInfo(SoySyntaxException.java:52)
        at com.google.template.soy.sharedpasses.ReportSyntaxVersionErrorsVisitor.exec(ReportSyntaxVersionErrorsVisitor.java:107)
        at com.google.template.soy.soyparse.SoyFileSetParser.runSingleFileCheckingPasses(SoyFileSetParser.java:322)
        at com.google.template.soy.soyparse.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:221)
        at com.google.template.soy.soyparse.SoyFileSetParser.parse(SoyFileSetParser.java:173)
        at com.google.template.soy.SoyFileSet.compileToJsSrcFiles(SoyFileSet.java:921)
        at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:303)
        at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
```

here is my Soy file:

```
{namespace ns.templates.cb}
{template .cb}
  <div>Hello world!</div>
{/template}
```

Any idea why it doesn't work?

**Comment by Vadorequest** [comment]
Fixed... It just needed the comments... Found out by reading it again in Github because my shell sucks (windows...)

https://stackoverflow.com/questions/11496430/why-am-i-missing-soydocs-for-my-soy-template

**Comment by protoEvangelion** [comment]
I'm on Ubuntu 17 and had the same issue.  Needed to add the comments as well.

**Comment by lukesandberg** [comment]
you might want to upgrade to a more recent version.  This requirement has
been removed
