### ISSUE TITLE
SoyToIncrementalDomSrcCompiler compilation error for anchors containing child elements with attribute

### ISSUE THREAD

**Issue by eduardolundgren** [google/closure-templates#88]
The way I could reproduce the following issue was when an anchor element containing a child with attributes is passed as content of any `kind="html"` attribute and wrapped on a `{if}` block. Removing `{if $items}` fixes the problem.

```html
{call Dropdown.render data="all"}
    {param body kind="html"}
        {if $items}
            {foreach $item in $items}
                <li>
                    <a href="{$item.href}">
                        <span class="{$item.icon}"></span>
                    </a>
                </li>
            {/foreach}
        {/if}
     {/param}
{/call}
```

```
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161)
	at com.google.template.soy.shared.internal.CodeBuilder.changeIndentHelper(CodeBuilder.java:106)
	at com.google.template.soy.shared.internal.CodeBuilder.increaseIndent(CodeBuilder.java:75)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.printAttributeList(GenIncrementalDomCodeVisitor.java:372)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.printStaticAndDynamicAttributes(GenIncrementalDomCodeVisitor.java:331)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitHtmlVoidTagNode(GenIncrementalDomCodeVisitor.java:579)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:35)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitChildren(GenIncrementalDomCodeVisitor.java:191)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitForeachNonemptyNode(GenJsCodeVisitor.java:1250)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:100)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitForeachNode(GenJsCodeVisitor.java:1185)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:99)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitChildren(GenIncrementalDomCodeVisitor.java:191)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitSoyNode(GenJsCodeVisitor.java:1468)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitIfCondNode(AbstractSoyNodeVisitor.java:255)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:92)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitIfNode(GenJsCodeVisitor.java:1027)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:91)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitChildren(GenIncrementalDomCodeVisitor.java:191)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitLetParamContentNode(GenIncrementalDomCodeVisitor.java:218)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitCallParamContentNode(GenIncrementalDomCodeVisitor.java:248)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:108)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitCallNode(GenIncrementalDomCodeVisitor.java:256)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitCallBasicNode(AbstractSoyNodeVisitor.java:295)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:105)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitChildren(GenIncrementalDomCodeVisitor.java:191)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.generateFunctionBody(GenIncrementalDomCodeVisitor.java:175)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitTemplateNode(GenJsCodeVisitor.java:778)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitTemplateNode(GenIncrementalDomCodeVisitor.java:158)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:155)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:63)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitSoyFileNode(GenJsCodeVisitor.java:399)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:61)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitSoyFileSetNode(GenJsCodeVisitor.java:306)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:60)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.gen(GenJsCodeVisitor.java:233)
	at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsSrc(IncrementalDomSrcMain.java:145)
	at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsFiles(IncrementalDomSrcMain.java:168)
	at com.google.template.soy.SoyFileSet.compileToIncrementalDomSrcFiles(SoyFileSet.java:1090)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.execMain(SoyToIncrementalDomSrcCompiler.java:179)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.access$100(SoyToIncrementalDomSrcCompiler.java:48)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler$1.main(SoyToIncrementalDomSrcCompiler.java:131)
	at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:195)
	at com.google.template.soy.MainClassUtils.run(MainClassUtils.java:188)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:127)
```

**Comment by sparhami** [comment]
Looks like it isn't happy about things being too indented in the generated code. I can bump up the limit of what it allows a bit.

**Comment by eduardolundgren** [comment]
Bump the limit of indentation would help. Thanks.

**Comment by eduardolundgren** [comment]
Did you include the indentation bump fix on the latest release?

**Comment by sparhami** [comment]
I can add a new version that includes it, just want to get in one more change first.

**Comment by eduardolundgren** [comment]
Thanks, this one will remove lots of work-arounds from our code to avoid deep indentation.

**Comment by sparhami** [comment]
Version 0.0.3 on npm should have this fixed.

**Comment by eduardolundgren** [comment]
Cool, thanks!

**Comment by eduardolundgren** [comment]
Just to confirm that it's working fine now. Thanks.
