### ISSUE TITLE
SoyToIncrementalDomSrcCompiler compilation error for HTML comments

### ISSUE THREAD

**Issue by eduardolundgren** [google/closure-templates#89]
When `<!DOCTYPE html>` is present and the following sequence of HTML comments followed by any element with attribute compilation fails. There might be a simpler way to reproduce this.

```html
{namespace Foo}

/**
 */
{template .template1}
	<!DOCTYPE html>
	<html>
		<head>
			<!-- -->
			<!-- -->
		</head>
		<body>
			<!-- -->
			<!-- -->
			<!-- -->
			<div attr="val"></div>
		</body>
	</html>
{/template}
```

```
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161)
	at com.google.template.soy.shared.internal.CodeBuilder.changeIndentHelper(CodeBuilder.java:106)
	at com.google.template.soy.shared.internal.CodeBuilder.increaseIndent(CodeBuilder.java:75)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.printAttributeList(GenIncrementalDomCodeVisitor.java:372)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.printStaticAndDynamicAttributes(GenIncrementalDomCodeVisitor.java:331)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitHtmlVoidTagNode(GenIncrementalDomCodeVisitor.java:579)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:35)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitChildren(GenIncrementalDomCodeVisitor.java:191)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.generateFunctionBody(GenIncrementalDomCodeVisitor.java:175)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitTemplateNode(GenJsCodeVisitor.java:778)
	at com.google.template.soy.incrementaldomsrc.GenIncrementalDomCodeVisitor.visitTemplateNode(GenIncrementalDomCodeVisitor.java:158)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visitTemplateBasicNode(AbstractSoyNodeVisitor.java:155)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:63)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitSoyFileNode(GenJsCodeVisitor.java:399)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:61)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.visitSoyFileSetNode(GenJsCodeVisitor.java:306)
	at com.google.template.soy.soytree.AbstractSoyNodeVisitor.visit(AbstractSoyNodeVisitor.java:60)
	at com.google.template.soy.html.AbstractHtmlSoyNodeVisitor.visit(AbstractHtmlSoyNodeVisitor.java:39)
	at com.google.template.soy.jssrc.internal.GenJsCodeVisitor.gen(GenJsCodeVisitor.java:233)
	at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsSrc(IncrementalDomSrcMain.java:145)
	at com.google.template.soy.incrementaldomsrc.IncrementalDomSrcMain.genJsFiles(IncrementalDomSrcMain.java:168)
	at com.google.template.soy.SoyFileSet.compileToIncrementalDomSrcFiles(SoyFileSet.java:1090)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.execMain(SoyToIncrementalDomSrcCompiler.java:179)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.access$100(SoyToIncrementalDomSrcCompiler.java:48)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler$1.main(SoyToIncrementalDomSrcCompiler.java:131)
	at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:195)
	at com.google.template.soy.MainClassUtils.run(MainClassUtils.java:188)
	at com.google.template.soy.SoyToIncrementalDomSrcCompiler.main(SoyToIncrementalDomSrcCompiler.java:127)
```

**Comment by hochhaus** [comment]
@eduardolundgren How you are building SoyToIncrementalDomSrcCompiler.jar? I don't see SoyToIncrementalDomSrcCompiler.java in the repo. Are you creating this stub yourself?

**Comment by eduardolundgren** [comment]
From here https://www.npmjs.com/package/closure-templates-incrementaldom

**Comment by hochhaus** [comment]
@eduardolundgren Thanks! I didn't realize that an "official" build had been released. I had been working around this using the patch I mentioned here.

https://groups.google.com/forum/#!msg/closure-templates-discuss/8p6JIdaWWj0/hIPerE7hEwAJ

**Comment by sparhami** [comment]
This one will probably take a bit of time to implement. Ultimately though, it will just strip the comments since Incremental DOM doesn't support `Comment` nodes.

**Comment by eduardolundgren** [comment]
Stripping the comments should be fine for now.

**Comment by mairatma** [comment]
This also seems to have been fixed in the most recent version. Thanks!

**Comment by eduardolundgren** [comment]
Thanks.
